name: Lint Code

on:
  push:
    branches:
      - main
      - 'backend'
  pull_request:
    branches:
      - 'backend'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: |
          cd backend && npm install

      - name: Run ESLint
        run: |
          cd backend && npm run lint
